CREATE TABLE "club_presentation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "club_presentation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"link" text NOT NULL,
	"publishedAt" timestamp with time zone NOT NULL,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "club_presentation" ADD CONSTRAINT "club_presentation_createdById_club_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."club_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "presentation_published_at_idx" ON "club_presentation" USING btree ("publishedAt");
