CREATE TABLE "club_about_member" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "club_about_member_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"position" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"email" varchar(255) DEFAULT '' NOT NULL,
	"quote" text DEFAULT '' NOT NULL,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "club_about_member" ADD CONSTRAINT "club_about_member_createdById_club_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."club_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "about_member_position_idx" ON "club_about_member" USING btree ("position");
